apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewogICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgImF1dGgiOiAiYVd4NVlTMWphR2w2YUc5MkxURTZaMmh3WDFwTVpYTmtaMU4yZWpkcFdVaFBNbkZTZUVkMFVFSmFabFJrVEZOS016SjJSRXB2WVE9PSIKICAgICAgICAgICAgICAgIH0KICAgICAgICB9LAoJImN1cnJlbnRDb250ZXh0IjogInBvZG1hbiIsCgkiY2xpUGx1Z2luc0V4dHJhRGlycyI6IFsKCQkiL29wdC9ob21lYnJldy9saWIvZG9ja2VyL2NsaS1wbHVnaW5zIgoJXQp9Cg==
type: kubernetes.io/dockerconfigjson
